// client/src/components/Pages/Results.vue
<template>
    <layout>
        <h1 class="text-3xl block mb-4">Resultaten toevoegen/wijzigen</h1>
        <Card>
            <form class="px-4 md:px-8 pt-3 md:pt-6 pb-4 md:pb-8">
                <div class="mb-4">
                    <label
                        class="block text-gray-700 text-sm font-bold mb-2"
                        for="checkbox"
                    >
                        Resultaten wijzigen?
                    </label>
                    <Toggle v-model="update" @change="updateChanged()" />
                </div>
                <div class="mb-4">
                    <label
                        class="block text-gray-700 text-sm font-bold mb-2"
                        for="match"
                    >
                        Wedstrijd
                    </label>
                    <select
                        id="match"
                        v-model="event"
                        @change="eventChanged()"
                        class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline mb-4"
                        v-if="!loading.events && matches.length > 0"
                    >
                        <option
                            v-for="event in matches"
                            v-bind:key="event.id"
                            :value="event"
                            >{{
                                `${event.id}. ${event.name} (${new Date(
                                    event.start,
                                ).toLocaleString('nl-NL')}): ${
                                    event.event_teams[0].team.name
                                } - ${event.event_teams[1].team.name}`
                            }}</option
                        >
                    </select>
                    <Alert
                        v-if="!loading.events && matches.length === 0"
                        class="mb-4"
                        message="Er zijn geen wedstrijden gevonden"
                    />
                    <img
                        v-if="loading.events"
                        width="25"
                        height="25"
                        src="/assets/img/loader.svg"
                    />
                </div>
                <Alert
                    class="mb-4"
                    message="Resultaten kunnen alleen toegevoegd/gewijzigd worden voor matches
            die maximaal 7 dagen geleden zijn aangemaakt."
                />
                <div class="flex flex-wrap flex-row">
                    <div class="w-full lg:w-1/2 pr-0 lg:pr-4">
                        <p class="mb-4">Team 1:</p>
                        <div class="mb-4">
                            <label
                                class="block text-gray-700 text-sm font-bold mb-2"
                                for="team_one_score"
                            >
                                Teamscore
                            </label>
                            <input
                                :class="{
                                    'has-errors':
                                        errors['teams.0.score'] !== undefined,
                                }"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="team_one_score"
                                type="number"
                                placeholder="0"
                                v-model="form.teams[0].score"
                            />
                            <p
                                v-if="errors['teams.0.score']"
                                class="text-red-500 text-xs italic"
                            >
                                {{ errors['teams.0.score'][0] }}
                            </p>
                        </div>
                        <div class="mb-4">
                            <label
                                class="block text-gray-700 text-sm font-bold mb-2"
                                for="team_one_crawl_score"
                            >
                                Kruipscore
                            </label>
                            <input
                                :class="{
                                    'has-errors':
                                        errors['teams.0.crawl_score'] !==
                                        undefined,
                                }"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="team_one_crawl_score"
                                type="number"
                                placeholder="0"
                                v-model="form.teams[0].crawl_score"
                            />
                            <p
                                v-if="errors['teams.0.crawl_score']"
                                class="text-red-500 text-xs italic"
                            >
                                {{ errors['teams.0.crawl_score'][0] }}
                            </p>
                        </div>
                    </div>
                    <div class="w-full lg:w-1/2 pl-0 lg:pl-4">
                        <p class="mb-4">Team 2:</p>
                        <div class="mb-4">
                            <label
                                class="block text-gray-700 text-sm font-bold mb-2"
                                for="team_two_score"
                            >
                                Teamscore
                            </label>
                            <input
                                :class="{
                                    'has-errors':
                                        errors['teams.1.score'] !== undefined,
                                }"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="team_two_score"
                                type="number"
                                placeholder="0"
                                v-model="form.teams[1].score"
                            />
                            <p
                                v-if="errors['teams.1.score']"
                                class="text-red-500 text-xs italic"
                            >
                                {{ errors['teams.1.score'][0] }}
                            </p>
                        </div>
                        <div class="mb-4">
                            <label
                                class="block text-gray-700 text-sm font-bold mb-2"
                                for="team_two_crawl_score"
                            >
                                Kruipscore
                            </label>
                            <input
                                :class="{
                                    'has-errors':
                                        errors['teams.1.crawl_score'] !==
                                        undefined,
                                }"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="team_two_crawl_score"
                                type="number"
                                placeholder="0"
                                v-model="form.teams[1].crawl_score"
                            />
                            <p
                                v-if="errors['teams.1.crawl_score']"
                                class="text-red-500 text-xs italic"
                            >
                                {{ errors['teams.1.crawl_score'][0] }}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="mb-4">
                    <label
                        class="block text-gray-700 text-sm font-bold mb-2"
                        for="note"
                    >
                        Note
                    </label>
                    <textarea
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        v-model="form.note"
                        id="note"
                    ></textarea>
                </div>
                <div class="flex flex-row">
                    <button
                        v-on:click.prevent="saveResults()"
                        v-bind:disabled="loading.results"
                        class="block mr-4 mb-4 text-center bg-blue-500 text-white text-sm font-bold px-4 py-3 rounded shadow-md hover:no-shadow hover:bg-blue-600"
                    >
                        <span v-if="!loading.results">Opslaan</span>
                        <span v-else><Loader /></span>
                    </button>
                    <button
                        v-if="update && form.event_id !== null"
                        v-on:click.prevent="deleteResult()"
                        class="block mb-4
                    text-center bg-red-500 text-white text-sm font-bold px-4
                    py-3 rounded shadow-md hover:no-shadow hover:bg-red-600"
                    >
                        <span v-if="!loading.deleteResult"
                            >Verwijder resultaat</span
                        >
                        <span v-else><Loader /></span>
                    </button>
                </div>
                <div
                    v-if="succeeded || failure"
                    :class="{
                        'alert--failure': failure,
                        'alert--success': succeeded,
                    }"
                    class="flex items-center text-white text-sm font-bold px-4 py-3"
                    role="alert"
                >
                    <p>{{ responseMessage }}</p>
                </div>
            </form>
        </Card>
    </layout>
</template>

<script>
import Layout from '@shared/Layout.vue';
import Card from '@shared/Card.vue';
import Loader from '@shared/Loader.vue';
import Alert from '@shared/Alert.vue';
import Toggle from '@shared/Form/Toggle.vue';

const defaultForm = {
    teams: [
        {
            score: null,
            crawl_score: null,
        },
        {
            score: null,
            crawl_score: null,
        },
    ],
    note: '',
};

export default {
    name: 'Results',
    components: {
        Layout,
        Card,
        Loader,
        Alert,
        Toggle,
    },
    props: {
        events: {},
    },
    data: function() {
        return {
            update: false,
            loading: {
                events: false,
                results: false,
                deleteResult: false,
            },
            succeeded: false,
            failure: false,
            matches: this.events,
            responseMessage: '',
            event: {},
            errors: [],
            form: {
                event_id: null,
                ...defaultForm,
            },
        };
    },
    methods: {
        eventChanged() {
            this.form = {
                ...this.form,
                ...{ event_id: this.event.id },
            };

            if (this.update) {
                this.form = {
                    ...this.form,
                    ...{
                        teams: [
                            {
                                score:
                                    this.event.event_teams[0].result.score || 0,
                                crawl_score:
                                    this.event.event_teams[0].result
                                        .crawl_score || 0,
                            },
                            {
                                score:
                                    this.event.event_teams[1].result.score || 0,
                                crawl_score:
                                    this.event.event_teams[1].result
                                        .crawl_score || 0,
                            },
                        ],
                        note: this.event.event_teams[0].result.note,
                    },
                };
            } else {
                this.form = {
                    ...this.form,
                    ...defaultForm,
                };
            }
        },
        updateChanged() {
            this.form.event_id = null;
            this.loading.events = true;

            let url = window.location;

            const queryParams = new URLSearchParams(window.location.search);

            url += queryParams.has('limited') ? '&' : '?';
            url += `statusType=${
                this.update ? 'with-results' : 'without-results'
            }`;

            this.$axios
                .get(url)
                .then((response) => {
                    this.matches = response.data.events;
                })
                .then(() => {
                    this.loading.events = false;
                });
        },
        saveResults() {
            this.loading.results = true;
            this.succeeded = false;
            this.failure = false;

            let url = '/api/match/result';

            let request = this.update
                ? this.$axios.put(url, this.form)
                : this.$axios.post(url, this.form);

            request
                .then((response) => {
                    this.succeeded = true;
                    this.responseMessage = response.data.message;
                })
                .catch((failure) => {
                    this.failure = true;
                    this.errors = failure.data.errors || [];
                    this.responseMessage = failure.data.message;
                    this.loading.results = false;
                })
                .then(() => {
                    this.loading.results = false;
                });
        },
        deleteResult() {
            this.loading.deleteResult = true;
            this.succeeded = false;
            this.failure = false;

            let url = `api/match/results/${this.form.event_id}`;

            this.$axios
                .delete(url)
                .then((response) => {
                    this.succeeded = true;
                    this.responseMessage = response.data.message;

                    this.matches = this.matches.filter((match) => {
                        return match.id !== this.form.event_id;
                    });

                    this.form = { event_id: null, ...defaultForm };
                })
                .catch((failure) => {
                    this.failure = true;
                    this.loading.deleteResult = false;
                    this.responseMessage = failure.data.message;
                })
                .then(() => {
                    this.loading.deleteResult = false;
                });
        },
    },
};
</script>

// angular/src/app/pages/results/results.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from 'src/app/services/http.service';
import { ActivatedRoute } from '@angular/router';

@Component({
    selector: 'app-results',
    templateUrl: './results.component.html',
    styleUrls: ['./results.component.scss'],
})
export class ResultsComponent implements OnInit {
    public id;
    public events;
    public index;
    public loading = false;
    public editResults = false;
    public statusType = 'without-results';
    public autoSelectedEvent = false;
    public team1Name = '';
    public team2Name = '';
    public results = {};
    public resResult = {};

    constructor(
        private httpService: HttpService,
        private _routeParams: ActivatedRoute
    ) {}

    ngOnInit() {
        this._routeParams.params.subscribe(params => {
            this.id = +params['id'];
        });
        this.getEvents(this.editResults);
    }

    getEvents(editResults) {
        if (editResults) {
            this.statusType = 'with-results';
            this.editResults = true;
        } else {
            this.statusType = 'without-results';
            this.editResults = false;
        }

        this.httpService.get(`events/${this.statusType}`).subscribe(
            data => {
                this.events = data;
                this.index = 0;

                // Select event based on route param (if available)
                if (!isNaN(this.id)) {
                    for (let event in this.events) {
                        if (this.events[event].id == this.id) {
                            this.index = event;
                        }
                    }
                }

                if (this.events[this.index] !== undefined) {
                    this.selectEvent(this.index);
                }
            },
            error => console.error(error)
        );
    }

    selectEvent(index) {
        this.index = index;
        this.results = {
            id: this.events[index].id,
        };
        this.id = this.events[index].id;

        if (this.editResults) {
            if (this.events[index].event_teams[0] !== undefined) {
                if (
                    this.events[index].event_teams[0].result.score !== undefined
                ) {
                    this.results['scoreTeam1'] = this.events[
                        index
                    ].event_teams[0].result.score;
                }
                if (
                    this.events[index].event_teams[0].result.crawl_score !==
                    undefined
                ) {
                    this.results['crawlsTeam1'] = this.events[
                        index
                    ].event_teams[0].result.crawl_score;
                }
                if (
                    this.events[index].event_teams[1].result.score !== undefined
                ) {
                    this.results['scoreTeam2'] = this.events[
                        index
                    ].event_teams[1].result.score;
                }
                if (
                    this.events[index].event_teams[1].result.crawl_score !==
                    undefined
                ) {
                    this.results['crawlsTeam2'] = this.events[
                        index
                    ].event_teams[1].result.crawl_score;
                }
                if (
                    this.events[index].event_teams[0].result.note !== undefined
                ) {
                    this.results['note'] = this.events[
                        index
                    ].event_teams[0].result.note;
                }
            }
        }

        this.setTeamNames(index);

        if (!this.autoSelectedEvent) {
            // Reset response result alert
            this.resResult = {};
        }

        this.autoSelectedEvent = false;
    }

    setTeamNames(index) {
        this.team1Name = '';
        this.team2Name = '';

        if (this.events[index] === undefined) {
            return;
        }
        if (this.events[index].event_teams[0].team.name !== undefined) {
            this.team1Name = this.events[index].event_teams[0].team.name;
        }
        if (this.events[index].event_teams[1].team.name !== undefined) {
            this.team2Name = this.events[index].event_teams[1].team.name;
        }
    }

    saveResults() {
        if (this.loading) {
            return;
        }

        if (this.results['crawlsTeam1'] === undefined) {
            this.results['crawlsTeam1'] = 0;
        }

        if (this.results['crawlsTeam2'] === undefined) {
            this.results['crawlsTeam2'] = 0;
        }

        this.loading = true;
        this.httpService
            .post(`match/result/${this.editResults}`, this.results)
            .subscribe(
                data => {
                    this.resResult = data;
                    this.resResult['success'] = true;
                    // Reset
                    this.team1Name = '';
                    this.team2Name = '';
                    this.results = {};
                    this.events.splice(this.index, 1);
                    this.autoSelectedEvent = true;
                    this.index = 0;

                    if (this.events[this.index] !== undefined) {
                        this.selectEvent(this.index);
                    }
                },
                error => {
                    this.resResult['success'] = false;
                    this.resResult['error'] = true;
                    this.resResult['errors'] = Object.values(error.data.errors);
                    this.resResult['msg'] = error.data.msg;
                    this.loading = false;
                },
                () => {
                    this.loading = false;
                }
            );
    }

    deleteResults() {
        if (
            !confirm(
                'Weet je zeker dat je het resultaat voor deze match wilt verwijderen?'
            )
        ) {
            return;
        }

        if (this.loading) {
            return;
        }

        this.loading = true;
        this.httpService.delete(`match/result/${this.results['id']}`).subscribe(
            data => {
                this.resResult = data;
                this.resResult['success'] = true;
                // Reset
                this.team1Name = '';
                this.team2Name = '';
                this.results = {};
                this.events.splice(this.index, 1);
                this.autoSelectedEvent = true;
                this.index = 0;

                if (this.events[this.index] !== undefined) {
                    this.selectEvent(this.index);
                }
            },
            error => {
                this.resResult['success'] = false;
                this.resResult['error'] = true;
                this.resResult['errors'] = Object.values(error.data.errors);
                this.resResult['msg'] = error.data.msg;
                this.loading = false;
            },
            () => {
                this.loading = false;
            }
        );
    }
}

<div class="grid-x">
    <div class="cell large-12">
        <h1 *ngIf="!editResults">Resultaten toevoegen</h1>
        <h1 *ngIf="editResults">Resultaten wijzigen</h1>
        <div class="add-results">
            <span>Resultaten wijzigen</span>
            <div class="switch large">
                <input
                    id="add-edit"
                    class="switch-input"
                    type="checkbox"
                    [ngModel]="editResults"
                    (ngModelChange)="getEvents($event)"
                />
                <label for="add-edit" class="switch-paddle">
                    <span class="show-for-sr">Resultaten wijzigen</span>
                    <span class="switch-active" aria-hidden="true">Ja</span>
                    <span class="switch-inactive" aria-hidden="true">Nee</span>
                </label>
            </div>

            <div class="">
                <label>Match</label>
                <select
                    [ngModel]="index"
                    (ngModelChange)="selectEvent($event, i)"
                >
                    <option
                        value="{{ i }}"
                        name="event"
                        *ngFor="let event of events; let i = index"
                    >
                        <span
                            >{{ event.id }}. {{ event.name }} ({{
                                event.start | date: 'dd-MM-yyyy HH:mm:ss'
                            }}):
                        </span>
                        <span
                            >{{ event.event_teams[0]?.team.name }} -
                            {{ event.event_teams[1]?.team.name }}</span
                        >
                    </option>
                </select>
                <span class="field-note"
                    >Resultaten kunnen alleen toegevoegd/gewijzigd worden voor
                    matches die maximaal 7 dagen geleden zijn aangemaakt.</span
                >
            </div>

            <div class="">
                <label>Team 1: {{ team1Name }}</label>
                <div class="input-group">
                    <span class="input-group-label">Teamscore</span>
                    <input
                        type="text"
                        class="input-group-field"
                        name="score-team-1"
                        [(ngModel)]="results.scoreTeam1"
                    />
                </div>

                <div class="input-group">
                    <span class="input-group-label">Kruipscore</span>
                    <input
                        type="text"
                        class="input-group-field"
                        name="crawls-team-1"
                        [(ngModel)]="results.crawlsTeam1"
                    />
                </div>
            </div>

            <div class="">
                <label>Team 2: {{ team2Name }}</label>
                <div class="input-group">
                    <span class="input-group-label">Teamscore</span>
                    <input
                        type="text"
                        class="input-group-field"
                        name="score-team-2"
                        [(ngModel)]="results.scoreTeam2"
                    />
                </div>

                <div class="input-group">
                    <span class="input-group-label">Kruipscore</span>
                    <input
                        type="text"
                        class="input-group-field"
                        name="crawls-team-2"
                        [(ngModel)]="results.crawlsTeam2"
                    />
                </div>
            </div>

            <div class="">
                <label>Commentaar</label>
                <textarea
                    name="note"
                    id="note"
                    [(ngModel)]="results.note"
                ></textarea>
            </div>

            <div class="">
                <a
                    class="success button"
                    [ngClass]="{ disabled: loading }"
                    (click)="saveResults()"
                    >Opslaan</a
                >
                <a
                    class="alert button"
                    [ngClass]="{ disabled: loading }"
                    (click)="deleteResults()"
                    *ngIf="editResults"
                    >Resultaten verwijderen</a
                >
            </div>

            <div
                class="success callout"
                [innerHTML]="resResult.msg"
                *ngIf="resResult.success"
            ></div>
            <div class="alert callout" *ngIf="resResult.error">
                <div>
                    {{ resResult.msg }}
                </div>
                <div *ngFor="let errorType of resResult.errors">
                    <span *ngFor="let error of errorType">
                        {{ error }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
