// angular/src/app/pages/players/players.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from 'src/app/services/http.service';

@Component({
    selector: 'app-players',
    templateUrl: './players.component.html',
    styleUrls: ['./players.component.scss'],
})
export class PlayersComponent implements OnInit {
    public loading = false;
    public resResult = {};
    public users;
    public player;

    constructor(private httpService: HttpService) {
        this.player = {
            default: false,
        };
    }

    ngOnInit() {
        this.getUsers();
    }

    getUsers() {
        this.httpService.get('users/slack').subscribe(
            data => {
                this.users = data;
                if (this.users[0] !== undefined) {
                    this.player = this.users[0];
                }
            },
            error => console.error(error),
            () => {}
        );
    }

    editList() {
        this.player.default = !this.player.default;
        this.loading = true;
        this.httpService.put('player', this.player).subscribe(
            data => {
                this.resResult = data;
                this.resResult['success'] = true;
            },
            error => {
                this.resResult['success'] = false;
                this.resResult['error'] = true;
                this.resResult['errors'] = Object.values(error.data.errors);
                this.resResult['msg'] = error.data.msg;
                this.loading = false;
                this.player.default = !this.player.default;
            },
            () => {
                this.loading = false;
            }
        );
    }

    selectPlayer($event, i) {
        this.player = $event;
        this.resResult = {};
    }
}

<div class="grid-x">
    <div class="cell large-12">
        <h1>Spelers</h1>
        <p>
            De spelerslijst bevat de spelers die standaard gekozen kunnen worden
            voor matches. Indien een speler niet in de spelerslijst staat, moet
            hij of zij iedere keer handmatig bij een matchaanvraag worden
            toegevoegd.
        </p>
        <div class="add-player">
            <div>
                <label>Speler</label>
                <select
                    [ngModel]="player"
                    (ngModelChange)="selectPlayer($event, i)"
                >
                    <option
                        [ngValue]="user"
                        name="user"
                        *ngFor="let user of users; let i = index"
                    >
                        <span
                            ><img
                                [src]="user.profile.image_48"
                                alt="{{ user.real_name }}"
                            />
                            {{ user.real_name }} (@{{ user.name }})</span
                        >
                    </option>
                </select>
            </div>

            <div>
                <a
                    class="alert button"
                    [ngClass]="{ disabled: loading }"
                    (click)="editList()"
                    *ngIf="player.default"
                    >Speler verwijderen van de spelerslijst</a
                >
                <a
                    class="success button"
                    [ngClass]="{ disabled: loading }"
                    (click)="editList()"
                    *ngIf="!player.default"
                    >Speler toevoegen aan de spelerslijst</a
                >
            </div>

            <div
                class="success callout"
                [innerHTML]="resResult.msg"
                *ngIf="resResult.success"
            ></div>
            <div class="alert callout" *ngIf="resResult.error">
                <div>
                    {{ resResult.msg }}
                </div>
                <div *ngFor="let errorType of resResult.errors">
                    <span *ngFor="let error of errorType">
                        {{ error }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

// client/src/components/Pages/Players.vue
<template>
    <layout>
        <h1 class="text-3xl block mb-4">Spelers</h1>
        <p class="mb-4">
            De spelerslijst bevat de spelers die standaard gekozen kunnen worden
            voor matches. Indien een speler niet in de spelerslijst staat, moet
            hij of zij iedere keer handmatig bij een matchaanvraag worden
            toegevoegd.
        </p>
        <Card class="px-4 md:px-8 pt-3 md:pt-6 pb-4 md:pb-8">
            <table class="text-left w-full border-collapse mb-4">
                <thead>
                    <TableHeader field="Speler" />
                    <TableHeader field="Standaardspeler" />
                </thead>
                <tbody>
                    <tr
                        v-for="player in players"
                        v-bind:key="player.id"
                        class="hover:bg-gray-300 border-b border-gray-300"
                    >
                        <td
                            class="flex flex-row content-start items-center py-2 px-3 text-sm"
                        >
                            <img
                                :src="player.profile.image_32"
                                class="mr-4"
                                alt="speler"
                            />
                            {{ player.real_name }} @{{ player.name }}
                        </td>
                        <td class="py-2 px-3 text-sm">
                            <Toggle
                                :value="player.default"
                                @change="changeDefault(player)"
                            />
                        </td>
                    </tr>
                </tbody>
            </table>
        </Card>
    </layout>
</template>

<script>
import Layout from '@shared/Layout.vue';
import Card from '@shared/Card.vue';
import Toggle from '@shared/Form/Toggle.vue';
import TableHeader from '@shared/Table/TableHeader.vue';

export default {
    name: 'Players',
    components: {
        Layout,
        Card,
        Toggle,
        TableHeader,
    },
    props: {
        data: Array,
    },
    data: function() {
        return {
            players: this.data,
        };
    },
    methods: {
        changeDefault(player) {
            player.default = !player.default;

            let url = `api/players/${player.id}`;

            this.$axios
                .put(url, { default: player.default })
                .then((response) => {
                    this.$toastService.add('success', response.data.message);
                })
                .catch((failure) => {
                    this.$toastService.add('failure', failure.data.message);
                    player.default = !player.default;
                });
        },
    },
};
</script>
